#!/usr/bin/env expect
spawn python /var/lib/irods/scripts/setup_irods.py
expect "iRODS user*:"
send "\r"
expect "iRODS group*:"
send "\r"
expect "Please select a number or choose 0 to enter a new value*:"
send "\r"
expect "ODBC driver for postgres*:"
send "\r"
expect "Database server's hostname or IP address*:"
send "\r"
expect "Database server's port*:"
send "\r"
expect "Database name*:"
send "\r"
expect "Database username*:"
send "\r"
expect "Please confirm*:"
send "yes\r"
expect "Database password:"
send "test\r"
expect "Salt for passwords stored in the database:"
send "salt\r"
expect "iRODS server's zone name*:"
send "\r"
expect "iRODS server's port*:"
send "\r"
expect "iRODS port range (begin)*:"
send "\r"
expect "iRODS port range (end)*:"
send "\r"
expect "Control Plane port*:"
send "\r"
expect "Schema Validation Base URI*:"
send "\r"
expect "iRODS server's administrator username*:"
send "\r"
expect "Please confirm*:"
send "yes\r"
expect "iRODS server's zone key:"
send "1\r"
expect "iRODS server's negotiation key (32 characters):"
send "12345678901234567890123456789012\r"
expect "Control Plane key (32 characters):"
send "1234567890123456789012345678901b\r"
expect "iRODS server's administrator password:"
send "admin\r"
expect "iRODS Vault directory*:"
send "\r"
expect eof

